### ISSUE TITLE
pkl file format

### ISSUE THREAD

**Issue by hiro-oda** [jianwang-mpi/SceneEgo#3]
Thanks for your excellent work!

Is the format of the pkl file that is the output of your method the same format as easymocap, frankmocap and Vibe?
I am planning to use this blender addon for rendering the results of the pose estimations ([https://github.com/carlosedubarreto/b3d_mocap_import](https://github.com/carlosedubarreto/b3d_mocap_import)) .

**Comment by jianwang-mpi** [comment]
no, unfortunately.

You can use python pickle to open it and see what is inside.

with open('xxx.pkl', 'rb') as f:
    data = pickle.load(f)

**Comment by hiro-oda** [comment]
Thank you for your response and for taking the time to address this issue. I understand.
